FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/orbital/index.html
COPY icon.png /usr/share/nginx/html/orbital/icon.png
COPY install.sh /usr/share/nginx/html/orbital/install.sh
COPY hero.png /usr/share/nginx/html/orbital/hero.png
COPY privacy.html /usr/share/nginx/html/orbital/privacy.html
