server {
    listen 8080;
    root /usr/share/nginx/html;
    port_in_redirect off;
    absolute_redirect off;

    location /orbital {
        try_files $uri $uri/ /orbital/index.html;
    }

    location /orbital/Orbital-1.0.dmg {
        alias /usr/share/nginx/html/orbital/downloads/Orbital-1.0.dmg;
        add_header Content-Disposition "attachment; filename=Orbital-1.0.dmg";
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location /orbital/Orbital-1.0.msi {
        alias /usr/share/nginx/html/orbital/downloads/Orbital-1.0.msi;
        add_header Content-Disposition "attachment; filename=Orbital-1.0.msi";
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location /orbital/install.sh {
        default_type text/plain;
    }
}
