server {
    listen 8080;
    root /usr/share/nginx/html;
    port_in_redirect off;
    absolute_redirect off;

    location /orbital/downloads/ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location /orbital/install.sh {
        default_type text/plain;
    }

    location /orbital {
        try_files $uri $uri/ /orbital/index.html;
    }
}
