services:
  orbital-website:
    build: .
    volumes:
      - ./downloads:/usr/share/nginx/html/orbital/downloads
    networks:
      - tunnel
    restart: unless-stopped

networks:
  tunnel:
    external: true
    name: cloudflared-tunnel-macmini_tunnel
