FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/orbital/index.html
COPY icon.png /usr/share/nginx/html/orbital/icon.png
COPY Orbital-1.0.dmg /usr/share/nginx/html/orbital/Orbital-1.0.dmg
