server {
    listen 8080;
    root /usr/share/nginx/html;

    location /orbital {
        try_files $uri $uri/ /orbital/index.html;
    }

    location /orbital/Orbital-1.0.dmg {
        add_header Content-Disposition "attachment; filename=Orbital-1.0.dmg";
    }
}
